/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  AddressLike,
  BaseContract,
  BigNumberish,
  BytesLike,
  ContractMethod,
  ContractRunner,
  EventFragment,
  FunctionFragment,
  Interface,
  Listener,
  Result,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedContractMethod,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedLogDescription,
} from './common';

export declare namespace AQueryProofExecutor {
  export type ProofPointsStruct = {
    a: [BigNumberish, BigNumberish];
    b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
    c: [BigNumberish, BigNumberish];
  };

  export type ProofPointsStructOutput = [
    a: [bigint, bigint],
    b: [[bigint, bigint], [bigint, bigint]],
    c: [bigint, bigint]
  ] & {
    a: [bigint, bigint];
    b: [[bigint, bigint], [bigint, bigint]];
    c: [bigint, bigint];
  };
}

export declare namespace BaseVoting {
  export type ProposalRulesStruct = {
    selector: BigNumberish;
    citizenshipWhitelist: BigNumberish[];
    identityCreationTimestampUpperBound: BigNumberish;
    identityCounterUpperBound: BigNumberish;
    sex: BigNumberish;
    birthDateLowerbound: BigNumberish;
    birthDateUpperbound: BigNumberish;
    expirationDateLowerBound: BigNumberish;
  };

  export type ProposalRulesStructOutput = [
    selector: bigint,
    citizenshipWhitelist: bigint[],
    identityCreationTimestampUpperBound: bigint,
    identityCounterUpperBound: bigint,
    sex: bigint,
    birthDateLowerbound: bigint,
    birthDateUpperbound: bigint,
    expirationDateLowerBound: bigint
  ] & {
    selector: bigint;
    citizenshipWhitelist: bigint[];
    identityCreationTimestampUpperBound: bigint;
    identityCounterUpperBound: bigint;
    sex: bigint;
    birthDateLowerbound: bigint;
    birthDateUpperbound: bigint;
    expirationDateLowerBound: bigint;
  };
}

export interface IDCardVotingInterface extends Interface {
  getFunction(
      nameOrSignature:
          | 'IDENTITY_LIMIT'
          | '__IDCardVoting_init'
          | 'execute'
          | 'executeNoir'
          | 'executeTD1'
          | 'executeTD1Noir'
          | 'getProposalRules'
          | 'getPublicSignals'
          | 'getPublicSignalsTD1'
          | 'getRegistrationSMT'
          | 'getVerifier'
          | 'implementation'
          | 'owner'
          | 'proposalsState'
          | 'proxiableUUID'
          | 'renounceOwnership'
          | 'transferOwnership'
          | 'upgradeTo'
          | 'upgradeToAndCall',
  ): FunctionFragment;

  getEvent(
      nameOrSignatureOrTopic:
          | 'AdminChanged'
          | 'BeaconUpgraded'
          | 'Initialized'
          | 'OwnershipTransferred'
          | 'Upgraded',
  ): EventFragment;

  encodeFunctionData(
      functionFragment: 'IDENTITY_LIMIT',
      values?: undefined,
  ): string;

  encodeFunctionData(
      functionFragment: '__IDCardVoting_init',
      values: [AddressLike, AddressLike, AddressLike],
  ): string;

  encodeFunctionData(
      functionFragment: 'execute',
      values: [
        BytesLike,
        BigNumberish,
        BytesLike,
        AQueryProofExecutor.ProofPointsStruct
      ],
  ): string;

  encodeFunctionData(
      functionFragment: 'executeNoir',
      values: [BytesLike, BigNumberish, BytesLike, BytesLike],
  ): string;

  encodeFunctionData(
      functionFragment: 'executeTD1',
      values: [
        BytesLike,
        BigNumberish,
        BytesLike,
        AQueryProofExecutor.ProofPointsStruct
      ],
  ): string;

  encodeFunctionData(
      functionFragment: 'executeTD1Noir',
      values: [BytesLike, BigNumberish, BytesLike, BytesLike],
  ): string;

  encodeFunctionData(
      functionFragment: 'getProposalRules',
      values: [BigNumberish],
  ): string;

  encodeFunctionData(
      functionFragment: 'getPublicSignals',
      values: [BytesLike, BigNumberish, BytesLike],
  ): string;

  encodeFunctionData(
      functionFragment: 'getPublicSignalsTD1',
      values: [BytesLike, BigNumberish, BytesLike],
  ): string;

  encodeFunctionData(
      functionFragment: 'getRegistrationSMT',
      values?: undefined,
  ): string;

  encodeFunctionData(
      functionFragment: 'getVerifier',
      values?: undefined,
  ): string;

  encodeFunctionData(
      functionFragment: 'implementation',
      values?: undefined,
  ): string;

  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;

  encodeFunctionData(
      functionFragment: 'proposalsState',
      values?: undefined,
  ): string;

  encodeFunctionData(
      functionFragment: 'proxiableUUID',
      values?: undefined,
  ): string;

  encodeFunctionData(
      functionFragment: 'renounceOwnership',
      values?: undefined,
  ): string;

  encodeFunctionData(
      functionFragment: 'transferOwnership',
      values: [AddressLike],
  ): string;

  encodeFunctionData(
      functionFragment: 'upgradeTo',
      values: [AddressLike],
  ): string;

  encodeFunctionData(
      functionFragment: 'upgradeToAndCall',
      values: [AddressLike, BytesLike],
  ): string;

  decodeFunctionResult(
      functionFragment: 'IDENTITY_LIMIT',
      data: BytesLike,
  ): Result;

  decodeFunctionResult(
      functionFragment: '__IDCardVoting_init',
      data: BytesLike,
  ): Result;

  decodeFunctionResult(functionFragment: 'execute', data: BytesLike): Result;

  decodeFunctionResult(
      functionFragment: 'executeNoir',
      data: BytesLike,
  ): Result;

  decodeFunctionResult(functionFragment: 'executeTD1', data: BytesLike): Result;

  decodeFunctionResult(
      functionFragment: 'executeTD1Noir',
      data: BytesLike,
  ): Result;

  decodeFunctionResult(
      functionFragment: 'getProposalRules',
      data: BytesLike,
  ): Result;

  decodeFunctionResult(
      functionFragment: 'getPublicSignals',
      data: BytesLike,
  ): Result;

  decodeFunctionResult(
      functionFragment: 'getPublicSignalsTD1',
      data: BytesLike,
  ): Result;

  decodeFunctionResult(
      functionFragment: 'getRegistrationSMT',
      data: BytesLike,
  ): Result;

  decodeFunctionResult(
      functionFragment: 'getVerifier',
      data: BytesLike,
  ): Result;

  decodeFunctionResult(
      functionFragment: 'implementation',
      data: BytesLike,
  ): Result;

  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;

  decodeFunctionResult(
      functionFragment: 'proposalsState',
      data: BytesLike,
  ): Result;

  decodeFunctionResult(
      functionFragment: 'proxiableUUID',
      data: BytesLike,
  ): Result;

  decodeFunctionResult(
      functionFragment: 'renounceOwnership',
      data: BytesLike,
  ): Result;

  decodeFunctionResult(
      functionFragment: 'transferOwnership',
      data: BytesLike,
  ): Result;

  decodeFunctionResult(functionFragment: 'upgradeTo', data: BytesLike): Result;

  decodeFunctionResult(
      functionFragment: 'upgradeToAndCall',
      data: BytesLike,
  ): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];

  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }

  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];

  export interface OutputObject {
    beacon: string;
  }

  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];

  export interface OutputObject {
    version: bigint;
  }

  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];

  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }

  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];

  export interface OutputObject {
    implementation: string;
  }

  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDCardVoting extends BaseContract {
  interface: IDCardVotingInterface;
  IDENTITY_LIMIT: TypedContractMethod<[], [bigint], 'view'>;
  __IDCardVoting_init: TypedContractMethod<
      [
        registrationSMT_: AddressLike,
        proposalsState_: AddressLike,
        votingVerifier_: AddressLike
      ],
      [void],
      'nonpayable'
  >;
  execute: TypedContractMethod<
      [
        registrationRoot_: BytesLike,
        currentDate_: BigNumberish,
        userPayload_: BytesLike,
        zkPoints_: AQueryProofExecutor.ProofPointsStruct
      ],
      [void],
      'nonpayable'
  >;
  executeNoir: TypedContractMethod<
      [
        registrationRoot_: BytesLike,
        currentDate_: BigNumberish,
        userPayload_: BytesLike,
        zkPoints_: BytesLike
      ],
      [void],
      'nonpayable'
  >;
  executeTD1: TypedContractMethod<
      [
        registrationRoot_: BytesLike,
        currentDate_: BigNumberish,
        userPayload_: BytesLike,
        zkPoints_: AQueryProofExecutor.ProofPointsStruct
      ],
      [void],
      'nonpayable'
  >;
  executeTD1Noir: TypedContractMethod<
      [
        registrationRoot_: BytesLike,
        currentDate_: BigNumberish,
        userPayload_: BytesLike,
        zkPoints_: BytesLike
      ],
      [void],
      'nonpayable'
  >;
  getProposalRules: TypedContractMethod<
      [proposalId_: BigNumberish],
      [BaseVoting.ProposalRulesStructOutput],
      'view'
  >;
  getPublicSignals: TypedContractMethod<
      [
        registrationRoot_: BytesLike,
        currentDate_: BigNumberish,
        userPayload_: BytesLike
      ],
      [string[]],
      'view'
  >;
  getPublicSignalsTD1: TypedContractMethod<
      [
        registrationRoot_: BytesLike,
        currentDate_: BigNumberish,
        userPayload_: BytesLike
      ],
      [string[]],
      'view'
  >;
  getRegistrationSMT: TypedContractMethod<[], [string], 'view'>;
  getVerifier: TypedContractMethod<[], [string], 'view'>;
  implementation: TypedContractMethod<[], [string], 'view'>;
  owner: TypedContractMethod<[], [string], 'view'>;
  proposalsState: TypedContractMethod<[], [string], 'view'>;
  proxiableUUID: TypedContractMethod<[], [string], 'view'>;
  renounceOwnership: TypedContractMethod<[], [void], 'nonpayable'>;
  transferOwnership: TypedContractMethod<
      [newOwner: AddressLike],
      [void],
      'nonpayable'
  >;
  upgradeTo: TypedContractMethod<
      [newImplementation: AddressLike],
      [void],
      'nonpayable'
  >;
  upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike],
      [void],
      'payable'
  >;
  filters: {
    'AdminChanged(address,address)': TypedContractEvent<
        AdminChangedEvent.InputTuple,
        AdminChangedEvent.OutputTuple,
        AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
        AdminChangedEvent.InputTuple,
        AdminChangedEvent.OutputTuple,
        AdminChangedEvent.OutputObject
    >;

    'BeaconUpgraded(address)': TypedContractEvent<
        BeaconUpgradedEvent.InputTuple,
        BeaconUpgradedEvent.OutputTuple,
        BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
        BeaconUpgradedEvent.InputTuple,
        BeaconUpgradedEvent.OutputTuple,
        BeaconUpgradedEvent.OutputObject
    >;

    'Initialized(uint8)': TypedContractEvent<
        InitializedEvent.InputTuple,
        InitializedEvent.OutputTuple,
        InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
        InitializedEvent.InputTuple,
        InitializedEvent.OutputTuple,
        InitializedEvent.OutputObject
    >;

    'OwnershipTransferred(address,address)': TypedContractEvent<
        OwnershipTransferredEvent.InputTuple,
        OwnershipTransferredEvent.OutputTuple,
        OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
        OwnershipTransferredEvent.InputTuple,
        OwnershipTransferredEvent.OutputTuple,
        OwnershipTransferredEvent.OutputObject
    >;

    'Upgraded(address)': TypedContractEvent<
        UpgradedEvent.InputTuple,
        UpgradedEvent.OutputTuple,
        UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
        UpgradedEvent.InputTuple,
        UpgradedEvent.OutputTuple,
        UpgradedEvent.OutputObject
    >;
  };

  connect(runner?: ContractRunner | null): IDCardVoting;

  waitForDeployment(): Promise<this>;

  queryFilter<TCEvent extends TypedContractEvent>(
      event: TCEvent,
      fromBlockOrBlockhash?: string | number | undefined,
      toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  queryFilter<TCEvent extends TypedContractEvent>(
      filter: TypedDeferredTopicFilter<TCEvent>,
      fromBlockOrBlockhash?: string | number | undefined,
      toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
      event: TCEvent,
      listener: TypedListener<TCEvent>,
  ): Promise<this>;

  on<TCEvent extends TypedContractEvent>(
      filter: TypedDeferredTopicFilter<TCEvent>,
      listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
      event: TCEvent,
      listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
      filter: TypedDeferredTopicFilter<TCEvent>,
      listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
      event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;

  listeners(eventName?: string): Promise<Array<Listener>>;

  removeAllListeners<TCEvent extends TypedContractEvent>(
      event?: TCEvent,
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
      key: string | FunctionFragment,
  ): T;

  getFunction(
      nameOrSignature: 'IDENTITY_LIMIT',
  ): TypedContractMethod<[], [bigint], 'view'>;

  getFunction(
      nameOrSignature: '__IDCardVoting_init',
  ): TypedContractMethod<
      [
        registrationSMT_: AddressLike,
        proposalsState_: AddressLike,
        votingVerifier_: AddressLike
      ],
      [void],
      'nonpayable'
  >;

  getFunction(
      nameOrSignature: 'execute',
  ): TypedContractMethod<
      [
        registrationRoot_: BytesLike,
        currentDate_: BigNumberish,
        userPayload_: BytesLike,
        zkPoints_: AQueryProofExecutor.ProofPointsStruct
      ],
      [void],
      'nonpayable'
  >;

  getFunction(
      nameOrSignature: 'executeNoir',
  ): TypedContractMethod<
      [
        registrationRoot_: BytesLike,
        currentDate_: BigNumberish,
        userPayload_: BytesLike,
        zkPoints_: BytesLike
      ],
      [void],
      'nonpayable'
  >;

  getFunction(
      nameOrSignature: 'executeTD1',
  ): TypedContractMethod<
      [
        registrationRoot_: BytesLike,
        currentDate_: BigNumberish,
        userPayload_: BytesLike,
        zkPoints_: AQueryProofExecutor.ProofPointsStruct
      ],
      [void],
      'nonpayable'
  >;

  getFunction(
      nameOrSignature: 'executeTD1Noir',
  ): TypedContractMethod<
      [
        registrationRoot_: BytesLike,
        currentDate_: BigNumberish,
        userPayload_: BytesLike,
        zkPoints_: BytesLike
      ],
      [void],
      'nonpayable'
  >;

  getFunction(
      nameOrSignature: 'getProposalRules',
  ): TypedContractMethod<
      [proposalId_: BigNumberish],
      [BaseVoting.ProposalRulesStructOutput],
      'view'
  >;

  getFunction(
      nameOrSignature: 'getPublicSignals',
  ): TypedContractMethod<
      [
        registrationRoot_: BytesLike,
        currentDate_: BigNumberish,
        userPayload_: BytesLike
      ],
      [string[]],
      'view'
  >;

  getFunction(
      nameOrSignature: 'getPublicSignalsTD1',
  ): TypedContractMethod<
      [
        registrationRoot_: BytesLike,
        currentDate_: BigNumberish,
        userPayload_: BytesLike
      ],
      [string[]],
      'view'
  >;

  getFunction(
      nameOrSignature: 'getRegistrationSMT',
  ): TypedContractMethod<[], [string], 'view'>;

  getFunction(
      nameOrSignature: 'getVerifier',
  ): TypedContractMethod<[], [string], 'view'>;

  getFunction(
      nameOrSignature: 'implementation',
  ): TypedContractMethod<[], [string], 'view'>;

  getFunction(
      nameOrSignature: 'owner',
  ): TypedContractMethod<[], [string], 'view'>;

  getFunction(
      nameOrSignature: 'proposalsState',
  ): TypedContractMethod<[], [string], 'view'>;

  getFunction(
      nameOrSignature: 'proxiableUUID',
  ): TypedContractMethod<[], [string], 'view'>;

  getFunction(
      nameOrSignature: 'renounceOwnership',
  ): TypedContractMethod<[], [void], 'nonpayable'>;

  getFunction(
      nameOrSignature: 'transferOwnership',
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;

  getFunction(
      nameOrSignature: 'upgradeTo',
  ): TypedContractMethod<
      [newImplementation: AddressLike],
      [void],
      'nonpayable'
  >;

  getFunction(
      nameOrSignature: 'upgradeToAndCall',
  ): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike],
      [void],
      'payable'
  >;

  getEvent(
      key: 'AdminChanged',
  ): TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
  >;

  getEvent(
      key: 'BeaconUpgraded',
  ): TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
  >;

  getEvent(
      key: 'Initialized',
  ): TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
  >;

  getEvent(
      key: 'OwnershipTransferred',
  ): TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
  >;

  getEvent(
      key: 'Upgraded',
  ): TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
  >;
}
