/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace RegistrationSimple {
  export type PassportStruct = {
    dgCommit: BigNumberish;
    dg1Hash: BytesLike;
    publicKey: BytesLike;
    passportHash: BytesLike;
    verifier: AddressLike;
  };

  export type PassportStructOutput = [
    dgCommit: bigint,
    dg1Hash: string,
    publicKey: string,
    passportHash: string,
    verifier: string
  ] & {
    dgCommit: bigint;
    dg1Hash: string;
    publicKey: string;
    passportHash: string;
    verifier: string;
  };
}

export declare namespace Groth16VerifierHelper {
  export type ProofPointsStruct = {
    a: [BigNumberish, BigNumberish];
    b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
    c: [BigNumberish, BigNumberish];
  };

  export type ProofPointsStructOutput = [
    a: [bigint, bigint],
    b: [[bigint, bigint], [bigint, bigint]],
    c: [bigint, bigint]
  ] & {
    a: [bigint, bigint];
    b: [[bigint, bigint], [bigint, bigint]];
    c: [bigint, bigint];
  };
}

export interface RegistrationSimpleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "REGISTRATION_SIMPLE_PREFIX"
      | "UPGRADE_INTERFACE_VERSION"
      | "__RegistrationSimple_init"
      | "getSigners"
      | "implementation"
      | "proxiableUUID"
      | "registerSimple"
      | "registerSimpleViaNoir"
      | "stateKeeper"
      | "updateSignerList"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Initialized" | "SignersListUpdated" | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "REGISTRATION_SIMPLE_PREFIX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "__RegistrationSimple_init",
    values: [AddressLike, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getSigners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerSimple",
    values: [
      BigNumberish,
      RegistrationSimple.PassportStruct,
      BytesLike,
      Groth16VerifierHelper.ProofPointsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSimpleViaNoir",
    values: [
      BigNumberish,
      RegistrationSimple.PassportStruct,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "stateKeeper",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateSignerList",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "REGISTRATION_SIMPLE_PREFIX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "__RegistrationSimple_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSigners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSimple",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSimpleViaNoir",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stateKeeper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSignerList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignersListUpdatedEvent {
  export type InputTuple = [signers: AddressLike[], actions: BigNumberish[]];
  export type OutputTuple = [signers: string[], actions: bigint[]];
  export interface OutputObject {
    signers: string[];
    actions: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RegistrationSimple extends BaseContract {
  connect(runner?: ContractRunner | null): RegistrationSimple;
  waitForDeployment(): Promise<this>;

  interface: RegistrationSimpleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  REGISTRATION_SIMPLE_PREFIX: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  __RegistrationSimple_init: TypedContractMethod<
    [stateKeeper_: AddressLike, signers_: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getSigners: TypedContractMethod<[], [string[]], "view">;

  implementation: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  registerSimple: TypedContractMethod<
    [
      identityKey_: BigNumberish,
      passport_: RegistrationSimple.PassportStruct,
      signature_: BytesLike,
      zkPoints_: Groth16VerifierHelper.ProofPointsStruct
    ],
    [void],
    "nonpayable"
  >;

  registerSimpleViaNoir: TypedContractMethod<
    [
      identityKey_: BigNumberish,
      passport_: RegistrationSimple.PassportStruct,
      signature_: BytesLike,
      zkPoints_: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  stateKeeper: TypedContractMethod<[], [string], "view">;

  updateSignerList: TypedContractMethod<
    [data_: BytesLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "REGISTRATION_SIMPLE_PREFIX"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "__RegistrationSimple_init"
  ): TypedContractMethod<
    [stateKeeper_: AddressLike, signers_: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getSigners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "implementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerSimple"
  ): TypedContractMethod<
    [
      identityKey_: BigNumberish,
      passport_: RegistrationSimple.PassportStruct,
      signature_: BytesLike,
      zkPoints_: Groth16VerifierHelper.ProofPointsStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerSimpleViaNoir"
  ): TypedContractMethod<
    [
      identityKey_: BigNumberish,
      passport_: RegistrationSimple.PassportStruct,
      signature_: BytesLike,
      zkPoints_: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stateKeeper"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateSignerList"
  ): TypedContractMethod<[data_: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "SignersListUpdated"
  ): TypedContractEvent<
    SignersListUpdatedEvent.InputTuple,
    SignersListUpdatedEvent.OutputTuple,
    SignersListUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "SignersListUpdated(address[],uint8[])": TypedContractEvent<
      SignersListUpdatedEvent.InputTuple,
      SignersListUpdatedEvent.OutputTuple,
      SignersListUpdatedEvent.OutputObject
    >;
    SignersListUpdated: TypedContractEvent<
      SignersListUpdatedEvent.InputTuple,
      SignersListUpdatedEvent.OutputTuple,
      SignersListUpdatedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
