/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace StateKeeper {
  export type CertificateInfoStruct = { expirationTimestamp: BigNumberish };

  export type CertificateInfoStructOutput = [expirationTimestamp: bigint] & {
    expirationTimestamp: bigint;
  };

  export type PassportInfoStruct = {
    activeIdentity: BytesLike;
    identityReissueCounter: BigNumberish;
  };

  export type PassportInfoStructOutput = [
    activeIdentity: string,
    identityReissueCounter: bigint
  ] & { activeIdentity: string; identityReissueCounter: bigint };

  export type IdentityInfoStruct = {
    activePassport: BytesLike;
    issueTimestamp: BigNumberish;
  };

  export type IdentityInfoStructOutput = [
    activePassport: string,
    issueTimestamp: bigint
  ] & { activePassport: string; issueTimestamp: bigint };
}

export interface StateKeeperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ICAO_PREFIX"
      | "REVOKED"
      | "UPGRADE_INTERFACE_VERSION"
      | "USED"
      | "__StateKeeper_init"
      | "__StateKeeper_init_v2"
      | "addBond"
      | "addCertificate"
      | "addOwners"
      | "certificatesSmt"
      | "changeICAOMasterTreeRoot"
      | "getCertificateInfo"
      | "getOwners"
      | "getPassportInfo"
      | "getRegistrationByKey"
      | "getRegistrations"
      | "icaoMasterTreeMerkleRoot"
      | "implementation"
      | "isOwner"
      | "isRegistration"
      | "proxiableUUID"
      | "registrationSmt"
      | "reissueBondIdentity"
      | "removeCertificate"
      | "removeOwners"
      | "renounceOwnership"
      | "revokeBond"
      | "updateRegistrationSet"
      | "upgradeToAndCall"
      | "useSignature"
      | "usedSignatures"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BondAdded"
      | "BondIdentityReissued"
      | "BondRevoked"
      | "CertificateAdded"
      | "CertificateRemoved"
      | "Initialized"
      | "OwnersAdded"
      | "OwnersRemoved"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ICAO_PREFIX",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "REVOKED", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USED", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "__StateKeeper_init",
    values: [AddressLike, AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "__StateKeeper_init_v2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addBond",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addCertificate",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addOwners",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "certificatesSmt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeICAOMasterTreeRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificateInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getOwners", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPassportInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistrationByKey",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistrations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "icaoMasterTreeMerkleRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistration",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registrationSmt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reissueBondIdentity",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeCertificate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOwners",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeBond",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRegistrationSet",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "useSignature",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedSignatures",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ICAO_PREFIX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "REVOKED", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USED", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "__StateKeeper_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "__StateKeeper_init_v2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addBond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addOwners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "certificatesSmt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeICAOMasterTreeRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificateInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOwners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPassportInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegistrationByKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegistrations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "icaoMasterTreeMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegistration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registrationSmt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reissueBondIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOwners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeBond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateRegistrationSet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "useSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedSignatures",
    data: BytesLike
  ): Result;
}

export namespace BondAddedEvent {
  export type InputTuple = [passportKey: BytesLike, identityKey: BytesLike];
  export type OutputTuple = [passportKey: string, identityKey: string];
  export interface OutputObject {
    passportKey: string;
    identityKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondIdentityReissuedEvent {
  export type InputTuple = [passportKey: BytesLike, identityKey: BytesLike];
  export type OutputTuple = [passportKey: string, identityKey: string];
  export interface OutputObject {
    passportKey: string;
    identityKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondRevokedEvent {
  export type InputTuple = [passportKey: BytesLike, identityKey: BytesLike];
  export type OutputTuple = [passportKey: string, identityKey: string];
  export interface OutputObject {
    passportKey: string;
    identityKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateAddedEvent {
  export type InputTuple = [
    certificateKey: BytesLike,
    expirationTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    certificateKey: string,
    expirationTimestamp: bigint
  ];
  export interface OutputObject {
    certificateKey: string;
    expirationTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateRemovedEvent {
  export type InputTuple = [certificateKey: BytesLike];
  export type OutputTuple = [certificateKey: string];
  export interface OutputObject {
    certificateKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnersAddedEvent {
  export type InputTuple = [newOwners: AddressLike[]];
  export type OutputTuple = [newOwners: string[]];
  export interface OutputObject {
    newOwners: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnersRemovedEvent {
  export type InputTuple = [removedOwners: AddressLike[]];
  export type OutputTuple = [removedOwners: string[]];
  export interface OutputObject {
    removedOwners: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StateKeeper extends BaseContract {
  connect(runner?: ContractRunner | null): StateKeeper;
  waitForDeployment(): Promise<this>;

  interface: StateKeeperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ICAO_PREFIX: TypedContractMethod<[], [string], "view">;

  REVOKED: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  USED: TypedContractMethod<[], [string], "view">;

  __StateKeeper_init: TypedContractMethod<
    [
      initialOwner_: AddressLike,
      registrationSmt_: AddressLike,
      certificatesSmt_: AddressLike,
      icaoMasterTreeMerkleRoot_: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  __StateKeeper_init_v2: TypedContractMethod<[], [void], "nonpayable">;

  addBond: TypedContractMethod<
    [
      passportKey_: BytesLike,
      passportHash_: BytesLike,
      identityKey_: BytesLike,
      dgCommit_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  addCertificate: TypedContractMethod<
    [certificateKey_: BytesLike, expirationTimestamp_: BigNumberish],
    [void],
    "nonpayable"
  >;

  addOwners: TypedContractMethod<
    [newOwners_: AddressLike[]],
    [void],
    "nonpayable"
  >;

  certificatesSmt: TypedContractMethod<[], [string], "view">;

  changeICAOMasterTreeRoot: TypedContractMethod<
    [newRoot_: BytesLike],
    [void],
    "nonpayable"
  >;

  getCertificateInfo: TypedContractMethod<
    [certificateKey_: BytesLike],
    [StateKeeper.CertificateInfoStructOutput],
    "view"
  >;

  getOwners: TypedContractMethod<[], [string[]], "view">;

  getPassportInfo: TypedContractMethod<
    [passportKey_: BytesLike],
    [
      [
        StateKeeper.PassportInfoStructOutput,
        StateKeeper.IdentityInfoStructOutput
      ] & {
        passportInfo_: StateKeeper.PassportInfoStructOutput;
        identityInfo_: StateKeeper.IdentityInfoStructOutput;
      }
    ],
    "view"
  >;

  getRegistrationByKey: TypedContractMethod<[key_: string], [string], "view">;

  getRegistrations: TypedContractMethod<
    [],
    [[string[], string[]] & { keys_: string[]; values_: string[] }],
    "view"
  >;

  icaoMasterTreeMerkleRoot: TypedContractMethod<[], [string], "view">;

  implementation: TypedContractMethod<[], [string], "view">;

  isOwner: TypedContractMethod<[address_: AddressLike], [boolean], "view">;

  isRegistration: TypedContractMethod<
    [registration_: AddressLike],
    [boolean],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  registrationSmt: TypedContractMethod<[], [string], "view">;

  reissueBondIdentity: TypedContractMethod<
    [passportKey_: BytesLike, identityKey_: BytesLike, dgCommit_: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeCertificate: TypedContractMethod<
    [certificateKey_: BytesLike],
    [void],
    "nonpayable"
  >;

  removeOwners: TypedContractMethod<
    [oldOwners_: AddressLike[]],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeBond: TypedContractMethod<
    [passportKey_: BytesLike, identityKey_: BytesLike],
    [void],
    "nonpayable"
  >;

  updateRegistrationSet: TypedContractMethod<
    [methodId_: BigNumberish, data_: BytesLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  useSignature: TypedContractMethod<
    [sigHash_: BytesLike],
    [void],
    "nonpayable"
  >;

  usedSignatures: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ICAO_PREFIX"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REVOKED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "__StateKeeper_init"
  ): TypedContractMethod<
    [
      initialOwner_: AddressLike,
      registrationSmt_: AddressLike,
      certificatesSmt_: AddressLike,
      icaoMasterTreeMerkleRoot_: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "__StateKeeper_init_v2"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addBond"
  ): TypedContractMethod<
    [
      passportKey_: BytesLike,
      passportHash_: BytesLike,
      identityKey_: BytesLike,
      dgCommit_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addCertificate"
  ): TypedContractMethod<
    [certificateKey_: BytesLike, expirationTimestamp_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addOwners"
  ): TypedContractMethod<[newOwners_: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "certificatesSmt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "changeICAOMasterTreeRoot"
  ): TypedContractMethod<[newRoot_: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCertificateInfo"
  ): TypedContractMethod<
    [certificateKey_: BytesLike],
    [StateKeeper.CertificateInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPassportInfo"
  ): TypedContractMethod<
    [passportKey_: BytesLike],
    [
      [
        StateKeeper.PassportInfoStructOutput,
        StateKeeper.IdentityInfoStructOutput
      ] & {
        passportInfo_: StateKeeper.PassportInfoStructOutput;
        identityInfo_: StateKeeper.IdentityInfoStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRegistrationByKey"
  ): TypedContractMethod<[key_: string], [string], "view">;
  getFunction(
    nameOrSignature: "getRegistrations"
  ): TypedContractMethod<
    [],
    [[string[], string[]] & { keys_: string[]; values_: string[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "icaoMasterTreeMerkleRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "implementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isOwner"
  ): TypedContractMethod<[address_: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRegistration"
  ): TypedContractMethod<[registration_: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registrationSmt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reissueBondIdentity"
  ): TypedContractMethod<
    [passportKey_: BytesLike, identityKey_: BytesLike, dgCommit_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeCertificate"
  ): TypedContractMethod<[certificateKey_: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeOwners"
  ): TypedContractMethod<[oldOwners_: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeBond"
  ): TypedContractMethod<
    [passportKey_: BytesLike, identityKey_: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateRegistrationSet"
  ): TypedContractMethod<
    [methodId_: BigNumberish, data_: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "useSignature"
  ): TypedContractMethod<[sigHash_: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedSignatures"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "BondAdded"
  ): TypedContractEvent<
    BondAddedEvent.InputTuple,
    BondAddedEvent.OutputTuple,
    BondAddedEvent.OutputObject
  >;
  getEvent(
    key: "BondIdentityReissued"
  ): TypedContractEvent<
    BondIdentityReissuedEvent.InputTuple,
    BondIdentityReissuedEvent.OutputTuple,
    BondIdentityReissuedEvent.OutputObject
  >;
  getEvent(
    key: "BondRevoked"
  ): TypedContractEvent<
    BondRevokedEvent.InputTuple,
    BondRevokedEvent.OutputTuple,
    BondRevokedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateAdded"
  ): TypedContractEvent<
    CertificateAddedEvent.InputTuple,
    CertificateAddedEvent.OutputTuple,
    CertificateAddedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateRemoved"
  ): TypedContractEvent<
    CertificateRemovedEvent.InputTuple,
    CertificateRemovedEvent.OutputTuple,
    CertificateRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnersAdded"
  ): TypedContractEvent<
    OwnersAddedEvent.InputTuple,
    OwnersAddedEvent.OutputTuple,
    OwnersAddedEvent.OutputObject
  >;
  getEvent(
    key: "OwnersRemoved"
  ): TypedContractEvent<
    OwnersRemovedEvent.InputTuple,
    OwnersRemovedEvent.OutputTuple,
    OwnersRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "BondAdded(bytes32,bytes32)": TypedContractEvent<
      BondAddedEvent.InputTuple,
      BondAddedEvent.OutputTuple,
      BondAddedEvent.OutputObject
    >;
    BondAdded: TypedContractEvent<
      BondAddedEvent.InputTuple,
      BondAddedEvent.OutputTuple,
      BondAddedEvent.OutputObject
    >;

    "BondIdentityReissued(bytes32,bytes32)": TypedContractEvent<
      BondIdentityReissuedEvent.InputTuple,
      BondIdentityReissuedEvent.OutputTuple,
      BondIdentityReissuedEvent.OutputObject
    >;
    BondIdentityReissued: TypedContractEvent<
      BondIdentityReissuedEvent.InputTuple,
      BondIdentityReissuedEvent.OutputTuple,
      BondIdentityReissuedEvent.OutputObject
    >;

    "BondRevoked(bytes32,bytes32)": TypedContractEvent<
      BondRevokedEvent.InputTuple,
      BondRevokedEvent.OutputTuple,
      BondRevokedEvent.OutputObject
    >;
    BondRevoked: TypedContractEvent<
      BondRevokedEvent.InputTuple,
      BondRevokedEvent.OutputTuple,
      BondRevokedEvent.OutputObject
    >;

    "CertificateAdded(bytes32,uint256)": TypedContractEvent<
      CertificateAddedEvent.InputTuple,
      CertificateAddedEvent.OutputTuple,
      CertificateAddedEvent.OutputObject
    >;
    CertificateAdded: TypedContractEvent<
      CertificateAddedEvent.InputTuple,
      CertificateAddedEvent.OutputTuple,
      CertificateAddedEvent.OutputObject
    >;

    "CertificateRemoved(bytes32)": TypedContractEvent<
      CertificateRemovedEvent.InputTuple,
      CertificateRemovedEvent.OutputTuple,
      CertificateRemovedEvent.OutputObject
    >;
    CertificateRemoved: TypedContractEvent<
      CertificateRemovedEvent.InputTuple,
      CertificateRemovedEvent.OutputTuple,
      CertificateRemovedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnersAdded(address[])": TypedContractEvent<
      OwnersAddedEvent.InputTuple,
      OwnersAddedEvent.OutputTuple,
      OwnersAddedEvent.OutputObject
    >;
    OwnersAdded: TypedContractEvent<
      OwnersAddedEvent.InputTuple,
      OwnersAddedEvent.OutputTuple,
      OwnersAddedEvent.OutputObject
    >;

    "OwnersRemoved(address[])": TypedContractEvent<
      OwnersRemovedEvent.InputTuple,
      OwnersRemovedEvent.OutputTuple,
      OwnersRemovedEvent.OutputObject
    >;
    OwnersRemoved: TypedContractEvent<
      OwnersRemovedEvent.InputTuple,
      OwnersRemovedEvent.OutputTuple,
      OwnersRemovedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
