// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct Proof Proof;
void __swift_bridge__$Proof$_free(void* self);

void* __swift_bridge__$Vec_Proof$new(void);
void __swift_bridge__$Vec_Proof$drop(void* vec_ptr);
void __swift_bridge__$Vec_Proof$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_Proof$pop(void* vec_ptr);
void* __swift_bridge__$Vec_Proof$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_Proof$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_Proof$len(void* vec_ptr);
void* __swift_bridge__$Vec_Proof$as_ptr(void* vec_ptr);

struct __private__OptionU32 __swift_bridge__$setup_srs_swift(void* circuit_bytecode, struct RustStr srs_path, bool recursive);
void* __swift_bridge__$prove_swift(void* circuit_bytecode, void* initial_witness, void* proof_type, bool recursive);
void* __swift_bridge__$get_verification_key_swift(void* circuit_bytecode);
struct __private__OptionBool __swift_bridge__$verify_swift(void* proof, void* vkey, void* proof_type);
void* __swift_bridge__$execute_swift(void* circuit_bytecode, void* initial_witness);
uint8_t const * __swift_bridge__$Proof$proof_data_ptr(void* self);
uintptr_t __swift_bridge__$Proof$proof_data_len(void* self);
uint8_t const * __swift_bridge__$Proof$vkey_data_ptr(void* self);
uintptr_t __swift_bridge__$Proof$vkey_data_len(void* self);


